# Generated by Django 5.0.14 on 2026-06-11 05:18

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contact_messages',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor')], max_length=20)),
                ('user_id', models.IntegerField()),
                ('document_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('pan', 'PAN'), ('pitch_deck', 'Pitch Deck')], max_length=20)),
                ('file_path', models.FileField(max_length=255, upload_to=core.models.document_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'documents',
            },
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('investor_id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('investor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('investor_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('investor_description', models.TextField(blank=True, null=True)),
                ('max_investment_range', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'investors',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Platform admin',
                'verbose_name_plural': 'Platform admins',
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('startup_id', models.AutoField(primary_key=True, serialize=False)),
                ('founder_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=150)),
                ('website_url', models.URLField(blank=True, max_length=255, null=True)),
                ('startup_description', models.TextField(blank=True, null=True)),
                ('funding_required', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'startups',
            },
        ),
        migrations.CreateModel(
            name='StartupCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Startup categories',
                'db_table': 'startup_categories',
            },
        ),
        migrations.CreateModel(
            name='InvestmentOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(db_column='investor_id', on_delete=django.db.models.deletion.CASCADE, related_name='investment_offers', to='core.investor')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='investment_offers', to='core.startup')),
            ],
            options={
                'db_table': 'investment_offers',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('investment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('funded_on', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(db_column='investor_id', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.investor')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.startup')),
            ],
            options={
                'db_table': 'investments',
            },
        ),
        migrations.CreateModel(
            name='FundingRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('open', 'Open'), ('funded', 'Funded'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='funding_requests', to='core.startup')),
            ],
            options={
                'db_table': 'funding_requests',
            },
        ),
        migrations.AddField(
            model_name='startup',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to='core.startupcategory'),
        ),
    ]
