# Generated by Django 5.2.15 on 2026-06-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationToken',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('user_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor')], max_length=20)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'email_verification_tokens',
            },
        ),
        migrations.AddField(
            model_name='investor',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
