# Generated by Django 5.2.15 on 2026-06-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_investor_is_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor'), ('admin', 'Admin')], max_length=20)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField()),
                ('location_or_link', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_by_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(db_column='investor_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.investor')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.startup')),
            ],
            options={
                'db_table': 'meetings',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('startup', 'Startup'), ('investor', 'Investor')], max_length=10)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(db_column='investor_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.investor')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.startup')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedStartup',
            fields=[
                ('saved_id', models.AutoField(primary_key=True, serialize=False)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.ForeignKey(db_column='investor_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_startups', to='core.investor')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_investors', to='core.startup')),
            ],
            options={
                'db_table': 'saved_startups',
                'unique_together': {('investor', 'startup')},
            },
        ),
    ]
