# Generated by Django 5.2.15 on 2026-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notification_document_remarks_meeting_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investor',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='startup',
            name='is_email_verified',
            field=models.BooleanField(default=True),
        ),
    ]
